//
//  List.swift
//  SwiftExample
//
//  Created by Khawar Shahzad on 01/01/2015.
//  Copyright (c) 2015 Khawar Shahzad. All rights reserved.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to
//  deal in the Software without restriction, including without limitation the
//  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
//  IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import UIKit

class List: NSObject {
   class func names() -> Array <String> {
      return ["4th Dimension/4D",
         "ABAP",
         "ABC",
         "ActionScript",
         "Ada",
         "Agilent VEE",
         "Algol",
         "Alice",
         "Angelscript",
         "Apex",
         "APL",
         "AppleScript",
         "Arc",
         "Arduino",
         "ASP",
         "AspectJ",
         "Assembly",
         "ATLAS",
         "Augeas",
         "AutoHotkey",
         "AutoIt",
         "AutoLISP",
         "Automator",
         "Avenue",
         "Awk",
         "Bash",
         "(Visual) Basic",
         "bc",
         "BCPL",
         "BETA",
         "BlitzMax",
         "Boo",
         "Bourne Shell",
         "Bro",
         "C",
         "C Shell",
         "C#",
         "C++",
         "C++/CLI",
         "C-Omega",
         "Caml",
         "Ceylon",
         "CFML",
         "cg",
         "Ch",
         "CHILL",
         "CIL",
         "CL (OS/400)",
         "Clarion",
         "Clean",
         "Clipper",
         "Clojure",
         "CLU",
         "COBOL",
         "Cobra",
         "CoffeeScript",
         "ColdFusion",
         "COMAL",
         "Common Lisp",
         "Coq",
         "cT",
         "Curl",
         "D",
         "Dart",
         "DCL",
         "DCPU-16 ASM",
         "Delphi/Object Pascal",
         "DiBOL",
         "Dylan",
         "E",
         "eC",
         "Ecl",
         "ECMAScript",
         "EGL",
         "Eiffel",
         "Elixir",
         "Emacs Lisp",
         "Erlang",
         "Etoys",
         "Euphoria",
         "EXEC",
         "F#",
         "Factor",
         "Falcon",
         "Fancy",
         "Fantom",
         "Felix",
         "Forth",
         "Fortran",
         "Fortress",
         "(Visual) FoxPro",
         "Gambas",
         "GNU Octave",
         "Go",
         "Google AppsScript",
         "Gosu",
         "Groovy",
         "Haskell",
         "haXe",
         "Heron",
         "HPL",
         "HyperTalk",
         "Icon",
         "IDL",
         "Inform",
         "Informix-4GL",
         "INTERCAL",
         "Io",
         "Ioke",
         "J",
         "J#",
         "JADE",
         "Java",
         "Java FX Script",
         "JavaScript",
         "JScript",
         "JScript.NET",
         "Julia",
         "Korn Shell",
         "Kotlin",
         "LabVIEW",
         "Ladder Logic",
         "Lasso",
         "Limbo",
         "Lingo",
         "Lisp",
         "Logo",
         "Logtalk",
         "LotusScript",
         "LPC",
         "Lua",
         "Lustre",
         "M4",
         "MAD",
         "Magic",
         "Magik",
         "Malbolge",
         "MANTIS",
         "Maple",
         "Mathematica",
         "MATLAB",
         "Max/MSP",
         "MAXScript",
         "MEL",
         "Mercury",
         "Mirah",
         "Miva",
         "ML",
         "Monkey",
         "Modula-2",
         "Modula-3",
         "MOO",
         "Moto",
         "MS-DOS Batch",
         "MUMPS",
         "NATURAL",
         "Nemerle",
         "Nimrod",
         "NQC",
         "NSIS",
         "Nu",
         "NXT-G",
         "Oberon",
         "Object Rexx",
         "Objective-C",
         "Objective-J",
         "OCaml",
         "Occam",
         "ooc",
         "Opa",
         "OpenCL",
         "OpenEdge ABL",
         "OPL",
         "Oz",
         "Paradox",
         "Parrot",
         "Pascal",
         "Perl",
         "PHP",
         "Pike",
         "PILOT",
         "PL/I",
         "PL/SQL",
         "Pliant",
         "PostScript",
         "POV-Ray",
         "PowerBasic",
         "PowerScript",
         "PowerShell",
         "Processing",
         "Prolog",
         "Puppet",
         "Pure Data",
         "Python",
         "Q",
         "R",
         "Racket",
         "REALBasic",
         "REBOL",
         "Revolution",
         "REXX",
         "RPG (OS/400)",
         "Ruby",
         "Rust",
         "S",
         "S-PLUS",
         "SAS",
         "Sather",
         "Scala",
         "Scheme",
         "Scilab",
         "Scratch",
         "sed",
         "Seed7",
         "Self",
         "Shell",
         "SIGNAL",
         "Simula",
         "Simulink",
         "Slate",
         "Smalltalk",
         "Smarty",
         "SPARK",
         "SPSS",
         "SQR",
         "Squeak",
         "Squirrel",
         "Standard ML",
         "Suneido",
         "SuperCollider",
         "Swift",
         "TACL",
         "Tcl",
         "Tex",
         "thinBasic",
         "TOM",
         "Transact-SQL",
         "Turing",
         "TypeScript",
         "Vala/Genie",
         "VBScript",
         "Verilog",
         "VHDL",
         "VimL",
         "Visual Basic .NET",
         "WebDNA",
         "Whitespace",
         "X10",
         "xBase",
         "XBase++",
         "Xen",
         "XPL",
         "XSLT",
         "XQuery",
         "yacc",
         "Yorick",
         "Z shell"]
   }
}
